apiVersion: v1
kind: Pod
metadata:
  name: echo
spec:
  restartPolicy: OnFailure
  containers:
    - name: echo
      image: busybox
      env:
        - name: HELLO
          value: Hello
        - name: WORLD
          valueFrom:
            configMapKeyRef:
              name: config
              key: world
              optional: false
        - name: NODE_NAME
          valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
      command:
        - sh
        - -c
        - echo "$HELLO, $WORLD from $POD_NAME@$NODE_NAME"
