apiVersion: v1
kind: Pod
metadata:
  name: pltsci-assignment-ssl
spec:
  initContainers:
    - name: echo
      image: nyyakko/pltsci-assignment-init-echo:latest
    - name: network-check
      image: nyyakko/pltsci-assignment-init-ping:latest
  containers:
    - name: pltsci-assignment
      image: nyyakko/pltsci-assignment:latest
      ports:
        - name: http
          containerPort: 8080
    - name: pltsci-assignment-ssl
      image: nyyakko/pltsci-assignment-ssl-proxy:latest
      ports:
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901
